.TH "types.h" 3 "Fri Jul 17 2015" "Version 4" "XPad detectors driver for AreaDetector (EPICS)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
types.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBADDR32\fP   unsigned long"
.br
.ti -1c
.RI "#define \fBCHAR8\fP   char"
.br
.ti -1c
.RI "#define \fBINT8\fP   signed char"
.br
.ti -1c
.RI "#define \fBUINT8\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBINT16\fP   signed short"
.br
.ti -1c
.RI "#define \fBUINT16\fP   unsigned short"
.br
.ti -1c
.RI "#define \fBINT32\fP   signed long"
.br
.ti -1c
.RI "#define \fBINT64\fP   long long"
.br
.ti -1c
.RI "#define \fBUINT64\fP   unsigned long long"
.br
.ti -1c
.RI "#define \fBUINT32\fP   unsigned long"
.br
.ti -1c
.RI "#define \fBFLOAT32\fP   float"
.br
.ti -1c
.RI "#define \fBFLOAT64\fP   double"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBADDR32\fP   unsigned long"
.SS "#define \fBCHAR8\fP   char"
.SS "#define \fBFLOAT32\fP   float"
.SS "#define \fBFLOAT64\fP   double"
.SS "#define \fBINT16\fP   signed short"
.SS "#define \fBINT32\fP   signed long"
.SS "#define \fBINT64\fP   long long"
.SS "#define \fBINT8\fP   signed char"
.SS "#define \fBUINT16\fP   unsigned short"
.SS "#define \fBUINT32\fP   unsigned long"
.SS "#define \fBUINT64\fP   unsigned long long"
.SS "#define \fBUINT8\fP   unsigned char"
.SH "Author"
.PP 
Generated automatically by Doxygen for XPad detectors driver for AreaDetector (EPICS) from the source code\&.
