.TH "xpadx_pck.h" 3 "Fri Jul 17 2015" "Version 4" "XPad detectors driver for AreaDetector (EPICS)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpadx_pck.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBget_pck\fP (FILE *, \fBINT16\fP *)"
.br
.ti -1c
.RI "int \fBput_pck\fP (\fBINT16\fP *, int, int, int)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBget_pck\fP (FILE *, \fBINT16\fP *)"
.SS "int \fBput_pck\fP (\fBINT16\fP *, int, int, int)"
.SH "Author"
.PP 
Generated automatically by Doxygen for XPad detectors driver for AreaDetector (EPICS) from the source code\&.
