.TH "xpadApp_registerRecordDeviceDriver.cpp" 3 "Wed Jul 15 2015" "Version 4" "XPad detectors driver for AreaDetector (EPICS)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpadApp_registerRecordDeviceDriver.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'epicsStdlib\&.h'\fP
.br
\fC#include 'iocsh\&.h'\fP
.br
\fC#include 'iocshRegisterCommon\&.h'\fP
.br
\fC#include 'registryCommon\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBrso_func\fP )(dbRecordType *pdbRecordType)"
.br
.ti -1c
.RI "typedef void(* \fBreg_func\fP )(void)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBxpadApp_registerRecordDeviceDriver\fP (DBBASE *pbase)"
.br
.ti -1c
.RI "static void \fBrrddCallFunc\fP (const iocshArgBuf *)"
.br
.ti -1c
.RI "static int \fBRegistration\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_aSubRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_aaiRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_aaoRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_acalcoutRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_aiRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_aoRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_asynRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_biRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_boRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_busyRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_calcRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_calcoutRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_compressRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_dfanoutRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_eventRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_fanoutRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_histogramRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_longinRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_longoutRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_lsiRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_lsoRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_mbbiRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_mbbiDirectRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_mbboRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_mbboDirectRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_permissiveRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_printfRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_scalcoutRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_scanparmRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_selRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_seqRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_sscanRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_sseqRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_stateRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_stringinRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_stringoutRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_subRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_subArrayRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_swaitRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_transformRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern rset * \fBpvar_rset_waveformRSET\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_aSubRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_aaiRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_aaoRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_acalcoutRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_aiRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_aoRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_asynRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_biRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_boRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_busyRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_calcRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_calcoutRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_compressRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_dfanoutRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_eventRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_fanoutRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_histogramRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_longinRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_longoutRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_lsiRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_lsoRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbbiRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbbiDirectRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbboRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbboDirectRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_permissiveRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_printfRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_scalcoutRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_scanparmRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_selRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_seqRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_sscanRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_sseqRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_stateRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_stringinRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_stringoutRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_subRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_subArrayRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_swaitRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_transformRecordSizeOffset\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBrso_func\fP \fBpvar_func_waveformRecordSizeOffset\fP"
.br
.ti -1c
.RI "static const char *const \fBrecordTypeNames\fP []"
.br
.ti -1c
.RI "static const recordTypeLocation \fBrtl\fP []"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAaiSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAaoSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devaCalcoutSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAiSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAiSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAiSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devTimestampAI\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAiGeneralTime\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynAiInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynAiInt32Average\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynAiFloat64\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynAiFloat64Average\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAiStats\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAiClusts\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAoSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAoSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAoSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynAoInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynAoFloat64\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devAoStats\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynRecordDevice\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBiSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBiSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBiSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBiDbState\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynBiInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynBiUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBoSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBoSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBoSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBoGeneralTime\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBoDbState\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynBoInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynBoUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBusySoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devBusySoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynBusyInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devCalcoutSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devCalcoutSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devEventSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devHistogramSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLiSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLiSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLiGeneralTime\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynLiInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynLiUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLoSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLoSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynLoInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynLoUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLsiSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLsoSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLsoSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devLsoStdio\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbbiSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbbiSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbbiSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynMbbiInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynMbbiUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbbiDirectSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbbiDirectSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbbiDirectSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynMbbiDirectUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbboSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbboSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbboSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynMbboInt32\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynMbboUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbboDirectSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbboDirectSoftRaw\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devMbboDirectSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynMbboDirectUInt32Digital\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devPrintfSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devPrintfSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devPrintfStdio\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devsCalcoutSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSiSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSiSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devTimestampSI\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSiGeneralTime\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynSiOctetCmdResponse\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynSiOctetWriteRead\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynSiOctetRead\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devStringinStats\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devStringinEnvVar\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devStringinEpics\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSoSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSoSoftCallback\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSoStdio\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynSoOctetWrite\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSASoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devSWaitIoEvent\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devWfSoft\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynWfOctetCmdResponse\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynWfOctetWriteRead\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynWfOctetRead\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynWfOctetWrite\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynInt8ArrayWfIn\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynInt8ArrayWfOut\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynInt16ArrayWfIn\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynInt16ArrayWfOut\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynInt32ArrayWfIn\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynInt32ArrayWfOut\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynInt32TimeSeries\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynFloat32ArrayWfIn\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynFloat32ArrayWfOut\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynFloat64ArrayWfIn\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynFloat64ArrayWfOut\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_asynFloat64TimeSeries\fP"
.br
.ti -1c
.RI "epicsShareExtern dset * \fBpvar_dset_devWaveformStats\fP"
.br
.ti -1c
.RI "static const char *const \fBdeviceSupportNames\fP []"
.br
.ti -1c
.RI "static const dset *const \fBdevsl\fP []"
.br
.ti -1c
.RI "epicsShareExtern drvet * \fBpvar_drvet_drvAsyn\fP"
.br
.ti -1c
.RI "static const char * \fBdriverSupportNames\fP []"
.br
.ti -1c
.RI "static struct drvet * \fBdrvsl\fP []"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDAttrRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDCircularBuffRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDColorConvertRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileHDF5Register\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileJPEGRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileMagickRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileNetCDFRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileNexusRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileNullRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileTIFFRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDOverlayRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDProcessRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDROIRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDROIStatRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDStatsRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDStdArraysRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDTransformRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_arrInitialize\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_arrayTestRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_asInitHooksRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_asSub\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_asynInterposeEosRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_asynInterposeFlushRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_asynRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_configMenuRegistrar\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_dbndInitialize\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_dbrestoreRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_drvAsynIPPortRegisterCommands\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_drvAsynIPServerPortRegisterCommands\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_interpRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_parseRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_saveDataRegistrar\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_save_restoreRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_subAveRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_syncInitialize\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_tsInitialize\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_xpadRegister\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_myAttrFunct1\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_myTimeStampSource\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_rebootProc\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_scanMon\fP"
.br
.ti -1c
.RI "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_scanMonInit\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_aCalcAsyncThreshold\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_aCalcLoopMax\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_aCalcPerformDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_aCalcPostfixDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_aCalcoutRecordDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_arrayTestDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_asCaDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_atExitDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern double *const \fBpvar_double_boHIGHlimit\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_boHIGHprecision\fP"
.br
.ti -1c
.RI "epicsShareExtern double *const \fBpvar_double_calcoutODLYlimit\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_calcoutODLYprecision\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_callbackParallelThreadsDefault\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_configMenuDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_dbBptNotMonotonic\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_dbRecordsOnceOnly\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_dbTemplateMaxVars\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_debugSubAve\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_debug_saveData\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_debug_saveDataMsg\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_devaCalcoutSoftDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_devsCalcoutSoftDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_eraseNDAttributes\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_histogramSDELprecision\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_interpDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_recDynLinkDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_recDynLinkQsize\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sCalcLoopMax\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sCalcPerformDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sCalcPostfixDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sCalcStackHW\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sCalcStackLW\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sCalcoutRecordDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_saveData_MessagePolicy\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_save_restoreDatedBackupFiles\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_save_restoreDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_save_restoreIncompleteSetsOk\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_save_restoreNumSeqFiles\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_save_restoreRemountThreshold\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_save_restoreSeqPeriodInSeconds\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_scanparmRecordDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern double *const \fBpvar_double_seqDLYlimit\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_seqDLYprecision\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sscanRecordConnectWaitSeconds\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sscanRecordDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sscanRecordDontCheckLimits\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sscanRecordLookupTime\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sscanRecordViewPos\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_sseqRecDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_swaitRecordDebug\fP"
.br
.ti -1c
.RI "epicsShareExtern int *const \fBpvar_int_transformRecordDebug\fP"
.br
.ti -1c
.RI "static struct iocshVarDef \fBvardefs\fP []"
.br
.ti -1c
.RI "static const iocshArg \fBrrddArg0\fP = {'pdbbase', iocshArgPdbbase}"
.br
.ti -1c
.RI "static const iocshArg * \fBrrddArgs\fP [] = {&\fBrrddArg0\fP}"
.br
.ti -1c
.RI "static const iocshFuncDef \fBrrddFuncDef\fP"
.br
.ti -1c
.RI "static int \fBdone\fP = \fBRegistration\fP()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* \fBreg_func\fP)(void)"
.SS "typedef int(* \fBrso_func\fP)(dbRecordType *pdbRecordType)"
.SH "Function Documentation"
.PP 
.SS "static int \fBRegistration\fP ()\fC [static]\fP"
.SS "static void \fBrrddCallFunc\fP (const iocshArgBuf *)\fC [static]\fP"
.SS "int \fBxpadApp_registerRecordDeviceDriver\fP (DBBASE *pbase)"
.SH "Variable Documentation"
.PP 
.SS "const char* const \fBdeviceSupportNames\fP[]\fC [static]\fP"
.SS "const dset* const \fBdevsl\fP[]\fC [static]\fP"
.SS "int \fBdone\fP = \fBRegistration\fP()\fC [static]\fP"
.SS "const char* \fBdriverSupportNames\fP[]\fC [static]\fP"\fBInitial value:\fP
.PP
.nf
 {
    'drvAsyn'}
.fi
.SS "struct drvet* \fBdrvsl\fP[]\fC [static]\fP"\fBInitial value:\fP
.PP
.nf
 {
    pvar_drvet_drvAsyn}
.fi
.SS "epicsShareExtern double* const \fBpvar_double_boHIGHlimit\fP"
.SS "epicsShareExtern double* const \fBpvar_double_calcoutODLYlimit\fP"
.SS "epicsShareExtern double* const \fBpvar_double_seqDLYlimit\fP"
.SS "epicsShareExtern drvet* \fBpvar_drvet_drvAsyn\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynAiFloat64\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynAiFloat64Average\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynAiInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynAiInt32Average\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynAoFloat64\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynAoInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynBiInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynBiUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynBoInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynBoUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynBusyInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynFloat32ArrayWfIn\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynFloat32ArrayWfOut\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynFloat64ArrayWfIn\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynFloat64ArrayWfOut\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynFloat64TimeSeries\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynInt16ArrayWfIn\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynInt16ArrayWfOut\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynInt32ArrayWfIn\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynInt32ArrayWfOut\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynInt32TimeSeries\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynInt8ArrayWfIn\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynInt8ArrayWfOut\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynLiInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynLiUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynLoInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynLoUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynMbbiDirectUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynMbbiInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynMbbiUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynMbboDirectUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynMbboInt32\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynMbboUInt32Digital\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynRecordDevice\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynSiOctetCmdResponse\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynSiOctetRead\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynSiOctetWriteRead\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynSoOctetWrite\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynWfOctetCmdResponse\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynWfOctetRead\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynWfOctetWrite\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_asynWfOctetWriteRead\fP"
.SS "epicsShareExtern dset* \fBpvar_dset_devAaiSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAaoSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devaCalcoutSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAiClusts\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAiGeneralTime\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAiSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAiSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAiSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAiStats\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAoSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAoSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAoSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devAoStats\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBiDbState\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBiSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBiSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBiSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBoDbState\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBoGeneralTime\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBoSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBoSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBoSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBusySoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devBusySoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devCalcoutSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devCalcoutSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devEventSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devHistogramSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLiGeneralTime\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLiSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLiSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLoSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLoSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLsiSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLsoSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLsoSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devLsoStdio\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbbiDirectSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbbiDirectSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbbiDirectSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbbiSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbbiSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbbiSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbboDirectSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbboDirectSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbboDirectSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbboSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbboSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devMbboSoftRaw\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devPrintfSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devPrintfSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devPrintfStdio\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSASoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devsCalcoutSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSiGeneralTime\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSiSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSiSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSoSoft\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSoSoftCallback\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSoStdio\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devStringinEnvVar\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devStringinEpics\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devStringinStats\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devSWaitIoEvent\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devTimestampAI\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devTimestampSI\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devWaveformStats\fP"
.SS "epicsShareExtern dset * \fBpvar_dset_devWfSoft\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_aaiRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_aaoRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_acalcoutRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_aiRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_aoRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_arrayTestRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_arrInitialize\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_asInitHooksRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_asSub\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_aSubRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_asynInterposeEosRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_asynInterposeFlushRegister\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_asynRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_asynRegister\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_biRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_boRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_busyRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_calcoutRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_calcRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_compressRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_configMenuRegistrar\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_dbndInitialize\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_dbrestoreRegister\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_dfanoutRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_drvAsynIPPortRegisterCommands\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_drvAsynIPServerPortRegisterCommands\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_eventRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_fanoutRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_histogramRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_interpRegister\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_longinRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_longoutRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_lsiRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_lsoRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbbiDirectRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbbiRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbboDirectRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_mbboRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDAttrRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDCircularBuffRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDColorConvertRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileHDF5Register\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileJPEGRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileMagickRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileNetCDFRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileNexusRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileNullRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDFileTIFFRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDOverlayRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDProcessRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDROIRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDROIStatRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDStatsRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDStdArraysRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_NDTransformRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_parseRegister\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_permissiveRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_printfRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_myAttrFunct1\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_myTimeStampSource\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_rebootProc\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_scanMon\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_register_func_scanMonInit\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_save_restoreRegister\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_saveDataRegistrar\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_scalcoutRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_scanparmRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_selRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_seqRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_sscanRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_sseqRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_stateRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_stringinRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_stringoutRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_subArrayRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_subAveRegister\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_subRecordSizeOffset\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_swaitRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_syncInitialize\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_transformRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_tsInitialize\fP"
.SS "epicsShareExtern \fBrso_func\fP \fBpvar_func_waveformRecordSizeOffset\fP"
.SS "epicsShareExtern \fBreg_func\fP \fBpvar_func_xpadRegister\fP"
.SS "epicsShareExtern int* const \fBpvar_int_aCalcAsyncThreshold\fP"
.SS "epicsShareExtern int* const \fBpvar_int_aCalcLoopMax\fP"
.SS "epicsShareExtern int* const \fBpvar_int_aCalcoutRecordDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_aCalcPerformDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_aCalcPostfixDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_arrayTestDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_asCaDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_atExitDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_boHIGHprecision\fP"
.SS "epicsShareExtern int* const \fBpvar_int_calcoutODLYprecision\fP"
.SS "epicsShareExtern int* const \fBpvar_int_callbackParallelThreadsDefault\fP"
.SS "epicsShareExtern int* const \fBpvar_int_configMenuDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_dbBptNotMonotonic\fP"
.SS "epicsShareExtern int* const \fBpvar_int_dbRecordsOnceOnly\fP"
.SS "epicsShareExtern int* const \fBpvar_int_dbTemplateMaxVars\fP"
.SS "epicsShareExtern int* const \fBpvar_int_debug_saveData\fP"
.SS "epicsShareExtern int* const \fBpvar_int_debug_saveDataMsg\fP"
.SS "epicsShareExtern int* const \fBpvar_int_debugSubAve\fP"
.SS "epicsShareExtern int* const \fBpvar_int_devaCalcoutSoftDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_devsCalcoutSoftDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_eraseNDAttributes\fP"
.SS "epicsShareExtern int* const \fBpvar_int_histogramSDELprecision\fP"
.SS "epicsShareExtern int* const \fBpvar_int_interpDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_recDynLinkDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_recDynLinkQsize\fP"
.SS "epicsShareExtern int* const \fBpvar_int_save_restoreDatedBackupFiles\fP"
.SS "epicsShareExtern int* const \fBpvar_int_save_restoreDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_save_restoreIncompleteSetsOk\fP"
.SS "epicsShareExtern int* const \fBpvar_int_save_restoreNumSeqFiles\fP"
.SS "epicsShareExtern int* const \fBpvar_int_save_restoreRemountThreshold\fP"
.SS "epicsShareExtern int* const \fBpvar_int_save_restoreSeqPeriodInSeconds\fP"
.SS "epicsShareExtern int* const \fBpvar_int_saveData_MessagePolicy\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sCalcLoopMax\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sCalcoutRecordDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sCalcPerformDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sCalcPostfixDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sCalcStackHW\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sCalcStackLW\fP"
.SS "epicsShareExtern int* const \fBpvar_int_scanparmRecordDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_seqDLYprecision\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sscanRecordConnectWaitSeconds\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sscanRecordDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sscanRecordDontCheckLimits\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sscanRecordLookupTime\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sscanRecordViewPos\fP"
.SS "epicsShareExtern int* const \fBpvar_int_sseqRecDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_swaitRecordDebug\fP"
.SS "epicsShareExtern int* const \fBpvar_int_transformRecordDebug\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_aaiRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_aaoRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_acalcoutRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_aiRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_aoRSET\fP"
.SS "epicsShareExtern rset* \fBpvar_rset_aSubRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_asynRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_biRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_boRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_busyRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_calcoutRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_calcRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_compressRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_dfanoutRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_eventRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_fanoutRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_histogramRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_longinRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_longoutRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_lsiRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_lsoRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_mbbiDirectRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_mbbiRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_mbboDirectRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_mbboRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_permissiveRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_printfRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_scalcoutRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_scanparmRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_selRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_seqRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_sscanRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_sseqRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_stateRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_stringinRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_stringoutRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_subArrayRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_subRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_swaitRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_transformRSET\fP"
.SS "epicsShareExtern rset * \fBpvar_rset_waveformRSET\fP"
.SS "const char* const \fBrecordTypeNames\fP[]\fC [static]\fP"\fBInitial value:\fP
.PP
.nf
 {
    'aSub', 'aai', 'aao', 'acalcout', 'ai', 'ao', 'asyn', 'bi', 'bo',
    'busy', 'calc', 'calcout', 'compress', 'dfanout', 'event', 'fanout',
    'histogram', 'longin', 'longout', 'lsi', 'lso', 'mbbi', 'mbbiDirect',
    'mbbo', 'mbboDirect', 'permissive', 'printf', 'scalcout', 'scanparm',
    'sel', 'seq', 'sscan', 'sseq', 'state', 'stringin', 'stringout',
    'sub', 'subArray', 'swait', 'transform', 'waveform'
}
.fi
.SS "const iocshArg \fBrrddArg0\fP = {'pdbbase', iocshArgPdbbase}\fC [static]\fP"
.SS "const iocshArg* \fBrrddArgs\fP[] = {&\fBrrddArg0\fP}\fC [static]\fP"
.SS "const iocshFuncDef \fBrrddFuncDef\fP\fC [static]\fP"\fBInitial value:\fP
.PP
.nf

    {'xpadApp_registerRecordDeviceDriver', 1, rrddArgs}
.fi
.SS "const recordTypeLocation \fBrtl\fP[]\fC [static]\fP"
.SS "struct iocshVarDef \fBvardefs\fP[]\fC [static]\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for XPad detectors driver for AreaDetector (EPICS) from the source code\&.
